[theme]
base="dark"
primaryColor="#4bff9f"
backgroundColor="#000000"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
initialSidebarState = "collapsed"

[ui]
# Enables wide mode
layout = "wide"
